import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import classesRouter from "./classes";
import subjectsRouter from "./subjects";
import gradesRouter from "./grades";
import attendanceRouter from "./attendance";
import assignmentsRouter from "./assignments";
import materialsRouter from "./materials";
import eventsRouter from "./events";
import announcementsRouter from "./announcements";
import dashboardRouter from "./dashboard";
import emailRouter from "./email";
import groupsRouter from "./groups";
import scheduleRouter from "./schedule";
import justificationsRouter from "./justifications";
import appointmentsRouter from "./appointments";
import notificationsRouter from "./notifications";
import behaviorNotesRouter from "./behaviorNotes";
import tutoringRouter from "./tutoring";
import quizzesRouter from "./quizzes";
import diaryRouter from "./diary";
import competenciesRouter from "./competencies";
import forumRouter from "./forum";
import pollsRouter from "./polls";
import fieldTripsRouter from "./fieldTrips";
import roomsRouter from "./rooms";
import analyticsRouter from "./analytics";
import certificatesRouter from "./certificates";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/users", usersRouter);
router.use("/classes", classesRouter);
router.use("/subjects", subjectsRouter);
router.use("/grades", gradesRouter);
router.use("/attendance", attendanceRouter);
router.use("/assignments", assignmentsRouter);
router.use("/materials", materialsRouter);
router.use("/events", eventsRouter);
router.use("/announcements", announcementsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/email", emailRouter);
router.use("/groups", groupsRouter);
router.use("/schedule", scheduleRouter);
router.use("/justifications", justificationsRouter);
router.use("/appointments", appointmentsRouter);
router.use("/notifications", notificationsRouter);
router.use("/behavior-notes", behaviorNotesRouter);
router.use("/tutoring", tutoringRouter);
router.use("/quizzes", quizzesRouter);
router.use("/diary", diaryRouter);
router.use("/competencies", competenciesRouter);
router.use("/student-competencies", competenciesRouter);
router.use("/forum", forumRouter);
router.use("/polls", pollsRouter);
router.use("/field-trips", fieldTripsRouter);
router.use("/rooms", roomsRouter);
router.use("/room-bookings", roomsRouter);
router.use("/analytics", analyticsRouter);
router.use("/certificates", certificatesRouter);

export default router;
